services:
  - type: web
    name: nova-tech-v2
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: BOT_NAME
        value: Nova Tech V2
      - key: BOT_OWNER
        value: Nova Tech
      - key: PREFIX
        value: .
      - key: PORT
        value: 5000